ActiveRecord::Base.transaction do
  specialty_array = [
    "Allergy and Immunology",
    "Anesthesiology",
    "Colon and Rectal Surgery",
    "Dermatology",
    "Emergency Medicine",
    "Family Medicine",
    "Internal Medicine",
    "Clinical Biochemical Genetics",
    "Clinical Cytogenetics",
    "Clinical Genetics (MD)",
    "Clinical Molecular Genetics",
    "Neurological Surgery",
    "Nuclear Medicine",
    "Obstetrics and Gynecology",
    "Ophthalmology",
    "Orthopaedic Surgery",
    "Otolaryngology",
    "Pathology-Anatomic/Pathology-Clinical",
    "Pathology - Anatomic",
    "Pathology - Clinical",
    "Pediatrics",
    "Physical Medicine and Rehabilitation",
    "Plastic Surgery",
    "Aerospace Medicine",
    "Occupational Medicine",
    "Public Health and General Preventive Medicine",
    "Psychiatry",
    "Neurology",
    "Neurology with Special Qualification in Child Neurology",
    "Diagnostic Radiology",
    "Interventional Radiology and Diagnostic Radiology",
    "Radiation Oncology",
    "Medical Physics",
    "Surgery",
    "Vascular Surgery",
    "Thoracic and Cardiac Surgery",
    "Urology",
    "Critical Care Medicine",
    "Hospice and Palliative Medicine",
    "Pain Medicine",
    "Pediatric Anesthesiology",
    "Sleep Medicine",
    "Dermatopathology",
    "Pediatric Dermatology",
    "Anesthesiology Critical Care Medicine",
    "Emergency Medical Services",
    "Hospice and Palliative Medicine",
    "Internal Medicine-Critical Care Medicine",
    "Medical Toxicology",
    "Pediatric Emergency Medicine",
    "Sports Medicine",
    "Undersea and Hyperbaric Medicine",
    "Adolescent Medicine",
    "Geriatric Medicine",
    "Hospice and Palliative Medicine",
    "Sleep Medicine",
    "Sports Medicine",
    "Adult Congenital Heart Disease",
    "Advanced Heart Failure and Transplant Cardiology",
    "Cardiovascular Disease",
    "Clinical Cardiac Electrophysiology",
    "Critical Care Medicine",
    "Endocrinology, Diabetes and Metabolism",
    "Gastroenterology",
    "Geriatric Medicine",
    "Hematology",
    "Hospice and Palliative Medicine",
    "Infectious Disease",
    "Interventional Cardiology",
    "Medical Oncology",
    "Nephrology",
    "Pulmonary Disease",
    "Rheumatology",
    "Sleep Medicine",
    "Sports Medicine",
    "Transplant Hepatology",
    "Medical Biochemical Genetics",
    "Molecular Genetic Pathology",
    "Critical Care Medicine",
    "Female Pelvic Medicine and Reconstructive Surgery",
    "Gynecologic Oncology",
    "Hospice and Palliative Medicine",
    "Maternal and Fetal Medicine",
    "Reproductive Endocrinology/Infertility",
    "Orthopaedic Sports Medicine",
    "Surgery of the Hand",
    "Neurotology",
    "Pediatric Otolaryngology",
    "Plastic Surgery Within the Head and Neck",
    "Sleep Medicine",
    "Blood Banking/Transfusion Medicine",
    "Clinical Informatics",
    "Cytopathology",
    "Dermatopathology",
    "Neuropathology",
    "Pathology - Chemical",
    "Pathology - Forensic",
    "Pathology - Hematology",
    "Pathology - Medical Microbiology",
    "Pathology - Molecular Genetic",
    "Pathology - Pediatric",
    "Adolescent Medicine",
    "Child Abuse Pediatrics",
    "Developmental-Behavioral Pediatrics",
    "Hospice and Palliative Medicine",
    "Medical Toxicology",
    "Neonatal-Perinatal Medicine",
    "Neurodevelopmental Disabilities",
    "Pediatric Cardiology",
    "Pediatric Critical Care Medicine",
    "Pediatric Emergency Medicine",
    "Pediatric Endocrinology",
    "Pediatric Gastroenterology",
    "Pediatric Hematology-Oncology",
    "Pediatric Infectious Diseases",
    "Pediatric Nephrology",
    "Pediatric Pulmonology",
    "Pediatric Rheumatology",
    "Pediatric Transplant Hepatology",
    "Sleep Medicine",
    "Sports Medicine",
    "Brain Injury Medicine",
    "Hospice and Palliative Medicine",
    "Neuromuscular Medicine",
    "Pain Medicine",
    "Pediatric Rehabilitation Medicine",
    "Spinal Cord Injury Medicine",
    "Sports Medicine",
    "Plastic Surgery Within the Head and Neck",
    "Surgery of the Hand",
    "Clinical Informatics",
    "Medical Toxicology",
    "Undersea and Hyperbaric Medicine",
    "Addiction Psychiatry",
    "Brain Injury Medicine",
    "Child and Adolescent Psychiatry",
    "Clinical Neurophysiology",
    "Epilepsy",
    "Forensic Psychiatry",
    "Geriatric Psychiatry",
    "Hospice and Palliative Medicine",
    "Neurodevelopmental Disabilities",
    "Neuromuscular Medicine",
    "Pain Medicine",
    "Psychosomatic Medicine",
    "Sleep Medicine",
    "Vascular Neurology",
    "Hospice and Palliative Medicine",
    "Neuroradiology",
    "Nuclear Radiology",
    "Pediatric Radiology",
    "Vascular and Interventional Radiology",
    "Complex General Surgical Oncology",
    "Hospice and Palliative Medicine",
    "Pediatric Surgery",
    "Surgery of the Hand",
    "Surgical Critical Care",
    "Congenital Cardiac Surgery",
    "Female Pelvic Medicine and Reconstructive Surgery",
    "Pediatric Urology",
    "General Practice",
    "None"
  ]

  Specialty.delete_all

  specialty_array.uniq!
  specialty_array.sort!

  specialty_array.each do |specialty|
    Specialty.create(name: specialty)
  end
end
