ActiveRecord::Base.transaction do
  StateMedicalBoard.delete_all
  
  StateMedicalBoard.create(name: "Alabama Board of Medical Examiners and Medical Licensure Commission of Alabama", state: "AL", country: "US")
  StateMedicalBoard.create(name: "Alaska State Medical Board", state: "AK", country: "US")
  StateMedicalBoard.create(name: "Arizona Board of Osteopathic Examiners in Medicine and Surgery", state: "AZ", country: "US")
  StateMedicalBoard.create(name: "Arizona Medical Board", state: "AZ" , country: "US")
  StateMedicalBoard.create(name: "Arkansas State Medical Board", state:"AR", country: "US")
  StateMedicalBoard.create(name: "Colorado Medical Board", state:"CO", country: "US")
  StateMedicalBoard.create(name: "Delaware Board of Medical Licensure and Discipline", state:"DE", country: "US")
  StateMedicalBoard.create(name: "District of Columbia Board of Medicine", state:"DC", country: "US")
  StateMedicalBoard.create(name: "Florida Department of Health, Division of Medical Quality Assurance (DOs)", state:"FL", country: "US")
  StateMedicalBoard.create(name: "Florida Department of Health, Division of Medical Quality Assurance (MDs)", state:"FL", country: "US")
  StateMedicalBoard.create(name: "Georgia Composite Medical Board", state:"GA", country: "US")
  StateMedicalBoard.create(name: "Hawaii Board of Medical Examiners", state:"HI", country: "US")
  StateMedicalBoard.create(name: "Idaho State Board of Medicine", state:"ID", country: "US")
  StateMedicalBoard.create(name: "Illinois Department of Professional Regulation", state:"IL", country: "US")
  StateMedicalBoard.create(name: "Iowa Board of Medicine", state:"IA", country: "US")
  StateMedicalBoard.create(name: "Kansas State Board of Healing Arts", state:"KS", country: "US")
  StateMedicalBoard.create(name: "Kentucky Board of Medical Licensure", state:"KY", country: "US")
  StateMedicalBoard.create(name: "Louisiana State Board of Medical Examiners", state:"LA", country: "US")
  StateMedicalBoard.create(name: "Maine Board of Licensure in Medicine", state:"ME", country: "US")
  StateMedicalBoard.create(name: "Maine Board of Osteopathic Licensure", state:"ME", country: "US")
  StateMedicalBoard.create(name: "Maryland Board of Physicians", state:"MD", country: "US")
  StateMedicalBoard.create(name: "Massachusetts Board of Registration in Medicine", state:"MA", country: "US")
  StateMedicalBoard.create(name: "Medical Board of California", state:"CA", country: "US")
  StateMedicalBoard.create(name: "Medical Licensing Board of Indiana", state:"IN", country: "US")
  StateMedicalBoard.create(name: "Michigan Board of Medicine", state:"MI", country: "US")
  StateMedicalBoard.create(name: "Michigan Board of Osteopathic Medicine & Surgery", state:"MI", country: "US")
  StateMedicalBoard.create(name: "Minnesota Board of Medical Practice", state:"MN", country: "US")
  StateMedicalBoard.create(name: "Mississippi State Board of Medical Licensure", state:"MS", country: "US")
  StateMedicalBoard.create(name: "Missouri Board of Registration for the Healing Arts", state:"MO", country: "US")
  StateMedicalBoard.create(name: "Montana Board of Medical Examiners", state:"MT", country: "US")
  StateMedicalBoard.create(name: "Nebraska Board of Medicine and Surgery", state:"NE", country: "US")
  StateMedicalBoard.create(name: "Nevada State Board of Medical Examiners", state:"NV", country: "US")
  StateMedicalBoard.create(name: "Nevada State Board of Osteopathic Medicine", state:"NV", country: "US")
  StateMedicalBoard.create(name: "New Hampshire Board of Medicine", state:"NH", country: "US")
  StateMedicalBoard.create(name: "New Jersey State Board of Medical Examiners", state:"NJ", country: "US")
  StateMedicalBoard.create(name: "New Mexico Board of Osteopathic Medical Examiners", state:"NM", country: "US")
  StateMedicalBoard.create(name: "New Mexico Medical Board", state:"NM", country: "US")
  StateMedicalBoard.create(name: "New York State Board for Medicine", state:"NY", country: "US")
  StateMedicalBoard.create(name: "North Carolina Medical Board", state:"NC", country: "US")
  StateMedicalBoard.create(name: "North Dakota State Board of Medical Examiners", state:"ND", country: "US")
  StateMedicalBoard.create(name: "Oklahoma Board of Medical Licensure and Supervision", state:"OK", country: "US")
  StateMedicalBoard.create(name: "Oklahoma State Board of Osteopathic Examiners", state:"OK", country: "US")
  StateMedicalBoard.create(name: "Oregon Medical Board", state:"OR", country: "US")
  StateMedicalBoard.create(name: "Osteopathic Medical Board of California", state:"CA", country: "US")
  StateMedicalBoard.create(name: "Pennsylvania State Board of Medicine", state:"PA", country: "US")
  StateMedicalBoard.create(name: "Pennsylvania State Board of Osteopathic Medicine", state:"PA", country: "US")
  StateMedicalBoard.create(name: "Rhode Island Board of Medical Licensure and Discipline", state:"RI", country: "US")
  StateMedicalBoard.create(name: "South Carolina Board of Medical Examiners", state:"SC", country: "US")
  StateMedicalBoard.create(name: "South Dakota Board of Medical and Osteopathic Examiners", state:"SD", country: "US")
  StateMedicalBoard.create(name: "State Medical Board of Ohio", state:"OH", country: "US")
  StateMedicalBoard.create(name: "State of Connecticut, Department of Public Health", state:"CT", country: "US")
  StateMedicalBoard.create(name: "State of Wisconsin Medical Examining Board", state:"WI", country: "US")
  StateMedicalBoard.create(name: "Tennessee Board of Osteopathic Examination", state:"TN", country: "US")
  StateMedicalBoard.create(name: "Tennessee Department of Health", state:"TN", country: "US")
  StateMedicalBoard.create(name: "Texas Medical Board", state:"TX", country: "US")
  StateMedicalBoard.create(name: "Utah Division of Occupational and Professional Licensing", state:"UT", country: "US")
  StateMedicalBoard.create(name: "Vermont Board of Medical Practice", state:"VT", country: "US")
  StateMedicalBoard.create(name: "Virginia Board of Medicine", state:"VA", country: "US")
  StateMedicalBoard.create(name: "Washington Board of Osteopathic Medicine and Surgery", state:"WA", country: "US")
  StateMedicalBoard.create(name: "Washington State Medical Quality Assurance Commission", state:"WA", country: "US")
  StateMedicalBoard.create(name: "West Virginia Board of Medicine", state:"WV", country: "US")
  StateMedicalBoard.create(name: "West Virginia Board of Osteopathy", state:"WV", country: "US")
  StateMedicalBoard.create(name: "Wyoming Board of Medicine", state:"WY", country: "US")
end
