OnlineLocation.destroy_all


OnlineLocation.create(:state=>"AR",:state_name=>"Arkansas",:country=>"US")
OnlineLocation.create(:state=>"DC",:state_name=>"Washington, D.C.",:country=>"US")
OnlineLocation.create(:state=>"DE",:state_name=>"Delaware",:country=>"US")
OnlineLocation.create(:state=>"FL",:state_name=>"Florida",:country=>"US")
OnlineLocation.create(:state=>"GA",:state_name=>"Georgia",:country=>"US")
OnlineLocation.create(:state=>"KS",:state_name=>"Kansas",:country=>"US")
OnlineLocation.create(:state=>"LA",:state_name=>"Louisiana",:country=>"US")
OnlineLocation.create(:state=>"MD",:state_name=>"Maryland",:country=>"US")
OnlineLocation.create(:state=>"MO",:state_name=>"Missouri",:country=>"US")
OnlineLocation.create(:state=>"MS",:state_name=>"Mississippi",:country=>"US")
OnlineLocation.create(:state=>"NC",:state_name=>"North Carolina",:country=>"US")
OnlineLocation.create(:state=>"OK",:state_name=>"Oklahoma",:country=>"US")
OnlineLocation.create(:state=>"SC",:state_name=>"South Carolina",:country=>"US")
OnlineLocation.create(:state=>"TN",:state_name=>"Tennessee",:country=>"US")
OnlineLocation.create(:state=>"TX",:state_name=>"Texas",:country=>"US")
OnlineLocation.create(:state=>"WV",:state_name=>"West Virginia",:country=>"US")
OnlineLocation.create(:state=>"AL",:state_name=>"Alabama",:country=>"US")
OnlineLocation.create(:state=>"CT",:state_name=>"Connecticut",:country=>"US")
OnlineLocation.create(:state=>"IA",:state_name=>"Iowa",:country=>"US")
OnlineLocation.create(:state=>"IL",:state_name=>"Illinois",:country=>"US")
OnlineLocation.create(:state=>"IN",:state_name=>"Indiana",:country=>"US")
OnlineLocation.create(:state=>"ME",:state_name=>"Maine",:country=>"US")
OnlineLocation.create(:state=>"MI",:state_name=>"Michigan",:country=>"US")
OnlineLocation.create(:state=>"MN",:state_name=>"Minnesota",:country=>"US")
OnlineLocation.create(:state=>"NE",:state_name=>"Nebraska",:country=>"US")
OnlineLocation.create(:state=>"NH",:state_name=>"New Hampshire",:country=>"US")
OnlineLocation.create(:state=>"NJ",:state_name=>"New Jersey",:country=>"US")
OnlineLocation.create(:state=>"NY",:state_name=>"New York",:country=>"US")
OnlineLocation.create(:state=>"OH",:state_name=>"Ohio",:country=>"US")
OnlineLocation.create(:state=>"RI",:state_name=>"Rhode Island",:country=>"US")
OnlineLocation.create(:state=>"VT",:state_name=>"Vermont",:country=>"US")
OnlineLocation.create(:state=>"WI",:state_name=>"Wisconsin",:country=>"US")
OnlineLocation.create(:state=>"CA",:state_name=>"California",:country=>"US")
OnlineLocation.create(:state=>"CO",:state_name=>"Colorado",:country=>"US")
OnlineLocation.create(:state=>"NM",:state_name=>"New Mexico",:country=>"US")
OnlineLocation.create(:state=>"NV",:state_name=>"Nevada",:country=>"US")
OnlineLocation.create(:state=>"UT",:state_name=>"Utah",:country=>"US")
OnlineLocation.create(:state=>"AZ",:state_name=>"Arizona",:country=>"US")
OnlineLocation.create(:state=>"ID",:state_name=>"Idaho",:country=>"US")
OnlineLocation.create(:state=>"MT",:state_name=>"Montana",:country=>"US")
OnlineLocation.create(:state=>"ND",:state_name=>"North Dakota",:country=>"US")
OnlineLocation.create(:state=>"OR",:state_name=>"Oregon",:country=>"US")
OnlineLocation.create(:state=>"SD",:state_name=>"South Dakota",:country=>"US")
OnlineLocation.create(:state=>"WA",:state_name=>"Washington",:country=>"US")
OnlineLocation.create(:state=>"WY",:state_name=>"Wyoming",:country=>"US")
OnlineLocation.create(:state=>"HI",:state_name=>"Hawaii",:country=>"US")
OnlineLocation.create(:state=>"AK",:state_name=>"Alaska",:country=>"US")
OnlineLocation.create(:state=>"KY",:state_name=>"Kentucky",:country=>"US")
OnlineLocation.create(:state=>"MA",:state_name=>"Massachusetts",:country=>"US")
OnlineLocation.create(:state=>"PA",:state_name=>"Pennsylvania",:country=>"US")
OnlineLocation.create(:state=>"VA",:state_name=>"Virginia",:country=>"US")
